alter session set container = orclpdb;

ALTER SYSTEM SET JOB_QUEUE_PROCESSES = 3;

CREATE TABLE JOB_LOG (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_name      VARCHAR2(50),
    run_date      DATE,
    status        VARCHAR2(20),
    error_message VARCHAR2(4000)
);

CREATE TABLE SOURCE_TABLE (
    id          NUMBER PRIMARY KEY,
    data_value  VARCHAR2(100),
    created_at  DATE DEFAULT SYSDATE
);

CREATE TABLE ARCHIVE_TABLE (
    id          NUMBER PRIMARY KEY,
    data_value  VARCHAR2(100),
    created_at  DATE,
    archived_at DATE DEFAULT SYSDATE
);


DELETE FROM SOURCE_TABLE;
DELETE FROM ARCHIVE_TABLE;
DELETE FROM JOB_LOG;
COMMIT;
--ВСТАВКА ДАННЫХ
INSERT INTO SOURCE_TABLE (id, data_value, created_at) VALUES
(1, 'Old record 1', SYSDATE - 60);

INSERT INTO SOURCE_TABLE (id, data_value, created_at) VALUES
(2, 'Old record 2', SYSDATE - 45);

INSERT INTO SOURCE_TABLE (id, data_value, created_at) VALUES
(3, 'Old record 3', SYSDATE - 31);

INSERT INTO SOURCE_TABLE (id, data_value, created_at) VALUES
(4, 'Recent record 1', SYSDATE - 10);

INSERT INTO SOURCE_TABLE (id, data_value, created_at) VALUES
(5, 'Recent record 2', SYSDATE - 1);

COMMIT;

CREATE OR REPLACE PACKAGE job_manager IS
    PROCEDURE run_job;
    PROCEDURE create_job;
    PROCEDURE remove_job;
    PROCEDURE run_now;
    FUNCTION is_running RETURN NUMBER   ;
END job_manager;
/

--ПАКЕТ
CREATE OR REPLACE PACKAGE BODY job_manager IS

    g_job_id NUMBER;

    PROCEDURE run_job IS
    BEGIN
        INSERT INTO ARCHIVE_TABLE (id, data_value, created_at)
        SELECT id, data_value, created_at
        FROM SOURCE_TABLE
        WHERE created_at < SYSDATE - 30;

        DELETE FROM SOURCE_TABLE
        WHERE created_at < SYSDATE - 30;

        INSERT INTO JOB_LOG(job_name, run_date, status)
        VALUES ('DBMS_JOB_COPY', SYSDATE, 'SUCCESS');

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            INSERT INTO JOB_LOG (job_name, run_date, status)
VALUES ('DBMS_JOB_COPY', SYSDATE, 'SUCCESS');

            ROLLBACK;
            RAISE;
    END run_job;

    PROCEDURE create_job IS
    BEGIN
        DBMS_JOB.SUBMIT(
            job => g_job_id,
            what => 'job_manager.run_job;',
            next_date => SYSDATE + 7,
            interval  => 'SYSDATE + 7'
        );
        COMMIT;
    END create_job;

    PROCEDURE remove_job IS
    BEGIN
        DBMS_JOB.REMOVE(g_job_id);
        COMMIT;
    END remove_job;

    PROCEDURE run_now IS
    BEGIN
        DBMS_JOB.RUN(g_job_id);
    END run_now;

    FUNCTION is_running RETURN NUMBER IS
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_cnt
    FROM USER_JOBS
    WHERE job = g_job_id
      AND broken = 'N';

    IF v_cnt > 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END is_running;


END job_manager;
/

--Выполнение пакета
BEGIN job_manager.create_job; END;
/
BEGIN job_manager.run_now; END;
/

SELECT job_manager.is_running FROM dual;

BEGIN job_manager.remove_job; END;
/

SELECT * FROM JOB_LOG;
SELECT * FROM SOURCE_TABLE;
SELECT * FROM ARCHIVE_TABLE;

SELECT COUNT(*) AS running_jobs
FROM USER_JOBS



